package com.example.dao;

import com.example.entity.DO.Teacher;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    int deleteByPrimaryKey(String tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    Teacher selectByPrimaryKey(String tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    int updateByPrimaryKey(Teacher record);
}