package com.example.entity.DO;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_id
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    private String sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_name
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_birth
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    private String sBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.s_sex
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    private String sSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_id
     *
     * @return the value of Student.s_id
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_id
     *
     * @param sId the value for Student.s_id
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public void setsId(String sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_name
     *
     * @return the value of Student.s_name
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_name
     *
     * @param sName the value for Student.s_name
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public void setsName(String sName) {
        this.sName = sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_birth
     *
     * @return the value of Student.s_birth
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public String getsBirth() {
        return sBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_birth
     *
     * @param sBirth the value for Student.s_birth
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public void setsBirth(String sBirth) {
        this.sBirth = sBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.s_sex
     *
     * @return the value of Student.s_sex
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.s_sex
     *
     * @param sSex the value for Student.s_sex
     *
     * @mbggenerated Sat Feb 19 20:20:43 CST 2022
     */
    public void setsSex(String sSex) {
        this.sSex = sSex;
    }
}