package com.example.entity.DO;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.t_id
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    private String tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.t_name
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    private String tName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.t_id
     *
     * @return the value of Teacher.t_id
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.t_id
     *
     * @param tId the value for Teacher.t_id
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    public void settId(String tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.t_name
     *
     * @return the value of Teacher.t_name
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.t_name
     *
     * @param tName the value for Teacher.t_name
     *
     * @mbggenerated Sat Feb 19 20:21:52 CST 2022
     */
    public void settName(String tName) {
        this.tName = tName;
    }
}